### ISSUE TITLE
Kinetics-210K title

### ISSUE THREAD

**Issue by ZhenxingZheng** [MCG-NJU/CPD-Video#2]
This work is excellent. It inspired me a lot. Could you please provide Kinetics-210K title? Thank you very much.

**Comment by LLLLLLI** [comment]
Hi @ZhenxingZheng, thanks for your asking. You can download Kinetics-210k titles from this [link](https://drive.google.com/file/d/1olCDmDcIHU7raZUMMUwFjm9Ukbhsfbn8/view). 

The dataset is organized in `"{video_id}\t{processed title}\t{original title}\n"` for each line.

**Comment by ZhenxingZheng** [comment]
> Hi @ZhenxingZheng, thanks for your asking. You can download Kinetics-210k titles from this [link](https://drive.google.com/file/d/1olCDmDcIHU7raZUMMUwFjm9Ukbhsfbn8/view).
> 
> The dataset is organized in `"{video_id}\t{processed title}\t{original title}\n"` for each line.

I have downloaded this file. Thanks a lot.

**Comment by SunDoge** [comment]
@ZhenxingZheng , hi, did you reproduce the experimental results on Kinetics? I have some trouble with the code. Thx.
